### ISSUE TITLE
Mason build system not portable

### ISSUE THREAD

**Issue by stevenback** [libfuse/libfuse.github.io#1]
The mason build tools are not available to generic Red Hat 6 boxes that due to policy can not use the extended repos. 
Can a Makefile alternative be provided?

**Comment by Nikratio** [comment]
Thanks for the report! Unfortunately this will only happen if someone commits to maintaining it - which is unlikely, because the lack of such a volunteer was the reason that Makefile (or, more precisely, autotools) support was removed a few releases ago.
